### ISSUE TITLE
[codemod][new] Nuxt - migration to v4

### ISSUE THREAD

**Issue by arshcodemod** [codemod-com/codemod#919]
### Migration details
[Official upgrade guide](https://nuxt.com/docs/getting-started/upgrade)

- [x] directory-structure- [[Codemod Studio Link](https://go.codemod.com/mN5XHG8)] -> #1011
- [ ] shared-prerender-data [[Codemod Studio Link](https://go.codemod.com/)] -> TBD
- [x] default-data-error-value [[Codemod Studio Link](https://go.codemod.com/u4Ej09j)] -> #886
- [x] remove-deprecated-values- [[Codemod Studio Link](https://go.codemod.com/bQ8BDCa)] -> #973 
- [ ] respect-defaults-useAsyncData-useFetch [[Codemod Studio Link](https://go.codemod.com/JN4zn50)] -> blocked
- [x] shallow-data-reactivity -> #722 / #695
- [x] absolute-watch-paths [[Codemod Studio Link](https://go.codemod.com/aawARMa)] -> #959 
- [ ] directory-index-scanning - [[Codemod Studio Link](https://go.codemod.com/)] -> TBD
- [x] template-compilation-changes  -> #958  
- [ ] removal-of-experimental-features TBD

**Comment by wattanx** [comment]
Hello!
Thank you for your excellent work!

These codemods do not support `.vue` files.
Most codemods would be better able to support `.vue` files.

How do I create an issue asking for support for `.vue` files?

I also have experience in creating codemods that support `vue` files, so I may be able to help.
https://github.com/wattanx/wattanx-converter/tree/main/packages/nuxt-bridge-migration-tools

**Comment by alexbit-codemod** [comment]
Thanks for your message. We have a utility that can extract js/ts from vue files. Also, in the near future, through vue supper in ast-grep engine, we will natively support vue files. 
I would love to chat more. Feel free to ping me on our slack if interested in contributing more. 
go.codemod.com/community

**Comment by kevincam3** [comment]
I get this error: [Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files]

**Comment by alexbit-codemod** [comment]
@kevincam3 thanks for reporting the issue. lets use this task for creating new nuxt codemods. if there is some faulty codemod, lets create a new issue [here](https://github.com/codemod-com/codemod/issues/new/choose).

**Comment by mohab-sameh** [comment]
Closing as completed. Guide to upgrading with codemods can be found [here](https://nuxt.com/docs/getting-started/upgrade#migrating-using-codemods). Issues with specific codemods can be reported in [`codemod-com/commons`](https://github.com/codemod-com/commons) temporarily. Soon, we'll move Nuxt codemods to Nuxt's GitHub org.
